local MyPath = "Blox2D.DataTypes."
Vector2 = require(MyPath.."vector2")
UDim = require(MyPath.."udim")
UDim2 = require(MyPath.."udim2")
Connection = require(MyPath.."connection")
ScriptSignal = require(MyPath.."scriptsignal")
Color3 = require(MyPath.."color3")
BrickColor = require(MyPath.."brickcolor")
Enum = require(MyPath.."enum")